name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.2'
        cabal-version: '3.0'

    - name: Build
      run: ghc -O2 reliability-theory.hs
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: reliability-theory-linux
        path: ./reliability-theory
